[package]
name = "no_std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
rayon = "1.6.1"
regex = "1.7.0"
tinyvec = "1.6.0"
